version: '3'

services:
  frontend:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: on-failure
    environment:
      - REACT_APP_API_HOST=backend
      - REACT_APP_API_PORT=3001
  backend:
    image: todobackend
    ports:
      - 3001:3001
    restart: on-failure
  tests:
    image: todotests
    depends_on:
      - frontend
    restart: on-failure
    environment:
      - FRONT_HOST=frontend
      - FRONT_PORT=3000